# Name: Mallory Myers
# Date: 12/11/2024
# Class DSCI 412
# Assignment: Creating a GitHub Account 

During the first week of this course I learned the process of loading and exporting data into RStudio which gave me a better grasp on the features associated with the application; I also learned about bias-variance tradeoff where a lower variance and bias are essential and fluctuate based on training data. The second week incorporated how to fix the issue of missing values, which can involve removing rows from datasets to get a conclusion. Another concept was transformation where normalization and log transformations can be applied to convert variables. The third week's module had the topic of linear regression as well as the application of this method using an example, where the value of unknown data is predicted based on other variable. The following week, logistic regression, where categorical outcomes are predicted and classification, approaches to predict qualitative responses, were focused upon. Week five brought up the discussion of generalized linear models where the normal linear model is generalized, being less restrictive and incorporating features to analyze data. The Poisson Regression method which gives the probability of events occurring within an interval was also featured within this week. The sixth week shifted focus on decision trees, which are models within machine learning that are easy to interpret, as well as random forests, where many decision trees are utilized with different sets of data. The next week focused on a more complex topic, clustering methods. The k-means clustering technique is discussed within the module and is explained as a method that groups data together based on similarities which makes the analysis process more simplistic. The final week of the course incorporated the topic of documentation, where reanalyzing previous work is essential. The week also involves GitHub and its commands on the application. 
